# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: eve-zephyr
      url-base: https://github.com/everedero

  projects:
    - name: zephyr
      remote: eve-zephyr
      revision: 9e8c58f5d5866
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis      # required by the ARM port
          - cmsis_6    # required by Zephyr 4.4 for Cortex-M CMSIS headers
          - hal_atmel  # required by Arduino Due (SAM3X8E)
          - hal_stm32  # required by the nucleo_f756zg board (STM32 based)
